### ISSUE TITLE
index field: "icons"

### ISSUE THREAD

**Issue by ccev** [UIcons/UIcons#10]
### Importance: essential
- Type: `xxx` (defined per-folder)

This is a list of all existing icon names, without the file endings. In the index.json it could look something like this:

```json
{
    "pokemon": {
        "icons": ["0", "1", "1_f156", "..."]
    },
    "pokestop": {
        "icons": ["0", "0_q", "0_q_i", "..."]
    }
}
```

**Comment by versx** [comment]
What other properties do you think would/should be added in between? File endings and?

**Comment by ccev** [comment]
Sorry, not sure what you mean. Can you elaborate? The list would only contain the file names

**Comment by versx** [comment]
> Sorry, not sure what you mean. Can you elaborate? The list would only contain the file names

I mean since we're making the root property sections an object instead of a list of available image names. What other properties other than `name`, `icons`, `extension`/`file_endings`, etc do you think would be useful/needed? (all are fine and well just curious of expansion, x/y size?)

**Comment by ccev** [comment]
Ahh, only useful thing i can think of are overlay values + icon size. Forgot about that and going to open an issue for that tomorrow.
