### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by ccev** [UIcons/UIcons#14]
I'm unsure on this, but I think UIcons could benefit from a proper versioning system. Please see this more of a thread to discuss possible solutions.

### Reasons a proper versioning system would be beneficial
When Pokestop Upgrades drop, we're likely going to change the Stop icon format, making it incompatible with our current naming scheme. Every tool that uses Stop icons will then have to implement this new format and every user will have to pull that fix. Icon creators will then also take a day or two to update the icons. So basically the average mapper will be confused and end up having broken Stop icons for a couple of days until everything is updated. Additionally, some tools might take longer to get updated, leaving the users with broken Stop icons for multiple weeks.

### How an icon creator would have to implement a new version
- Copy the whole repo to a new branch or folder. Call those e.g. `HOME_outline_v1` and `HOME_outline_v2`
- Implement the changes
- Leave the old version untouched and maybe delete it after 5 months or so

### How a tool dev would have to implement the new version
- Change the repo URL
- Implement the changes

This way, if Stop Upgrades drop, icon creators can adjust their repos. Then the tool devs can implement the change. Then the users can pull. Without ever getting broken icons.

**Comment by jepke** [comment]
If breaking changes are needed in naming scheme, it automatically means front backends and tools need to adopt at the same time in 99.99% of cases.

For example the pokestop level thing. Leave the old icons in the folder and just create new icons along side, both old and new will be in the index.json.

If a icon creator decides to remove them the fallback will pick something that is the best match. Its up to the devs to keep everything up to date. If a project does not support pokestop levels after 5 months their dev needs to wake up.

**Comment by ccev** [comment]
That's a good idea actually. Just not deleting old icons. I can see this becoming a bit confusing but i don't expect many breaking changes at all.

That's the way to go then.
