### ISSUE TITLE
index.json base option 2

### ISSUE THREAD

**Issue by whitewillem** [UIcons/UIcons#17]
Simple and flat index file including file extentions.

```json
{
    "misc": [
        "..."
    ],
    "weather": [
        "..."
    ],
    "team": [
        "..."
    ],
    "gym": [
        "..."
    ],
    "pokestop": [
        "..."
    ],
    "type": [
        "..."
    ],
    "invasion": [
        "..."
    ],
    "raid-egg": [
        "..."
    ],
    "reward": {
        "item": [
            "..."
        ],
        "stardust": [
            "..."
        ],
        "candy": [
            "..."
        ],
        "pokecoin": [
            "..."
        ],
        "xl_candy": [
            "..."
        ],
        "sticker": [
            "..."
        ],
        "mega_resource": [
            "..."
        ]
    },
    "pokemon": [
        "..."
    ]
}
```

**Comment by ccev** [comment]
Can you list any advantages this has over my suggestions?

**Comment by whitewillem** [comment]
As i dont think we need any of it i didnt make room for it. But thats a simple change if any of it gets approved. With that in mind the only real difference is i added file extentions. And since you only ask for 1 advantage: this does allow multiple file extentions to be in the same folder where your version does not.

**Comment by ccev** [comment]
Indeed it does. But there's no way let the program know which extensions would be supported.

**Comment by jepke** [comment]
> Indeed it does. But there's no way let the program know which extensions would be supported.

There is absolutely no reason to list the file extension separately and strip it from all files. Whoever is going to config the repo should know beforehand if the repo offers png apng gif jpeg etc etc.

**Comment by ccev** [comment]
It'd be nice if it the file extension doesn't matter to the frontend. So e.g. PMSF could have GIF icons as well as PNGs

**Comment by jepke** [comment]
you're referring PMSF a lot in your icon discussion. Icon standard should not be based on pmsf but standalone in such a way everyone can implement in a simple manor.

Just make this index as willem suggests and if any project needs more details create a meta.json as separate file. Projects can then choose whether or not to use it. Pmsf wil not use any more details then just a plain index.

**Comment by whitewillem** [comment]
Im pmsf terms we can just set a extention in config for each url. So you could add the same repo twice but with png and with gif for example. User can then choose. You could also make a preferedExtention array part of fallback code. Many routes for the same thing. All depends on the project.

**Comment by versx** [comment]
> Indeed it does. But there's no way let the program know which extensions would be supported.

Configs are a thing
