### ISSUE TITLE
index.json base

### ISSUE THREAD

**Issue by ccev** [UIcons/UIcons#9]
## Describe why this should be changed or added
I'd like to get proper discussion on an index.json format going. These are my suggestions for a possible base.

- index.json should be a single file in the root of the UIcons iconset. Sitting at the same level as pokemon/pokestop/gym/... folders.
- Its purpose is to allow devs to easily support the repo.
- this format allows for more values than just a list of existing files. Like file extension, overlay values or metadata. I've opened an issue for each field i found useful, please check out these as well.

Its base should look like this:

```json
{
    "yyy": "yyy",
    "gym": {
        "xxx": "xxx"
    },
    "raid": {
        "xxx": "xxx"
    },
    "invasion": {
        "xxx": "xxx"
    },
    "pokemon": {
        "xxx": "xxx"
    },
    "pokestop": {
        "xxx": "xxx"
    },
    "reward": {
        "item": {
            "xxx": "xxx"
        },
        "stardust": {
            "xxx": "xxx"
        },
        "candy": {
            "xxx": "xxx"
        },
        "xl_candy": {
            "xxx": "xxx"
        },
        "mega_resource": {
            "xxx": "xxx"
        }
    },
    "team": {
        "xxx": "xxx"
    },
    "type": {
        "xxx": "xxx"
    },
    "weather": {
        "xxx": "xxx"
    },
    "misc": {
        "xxx": "xxx"
    }
}
```

- `"xxx": "xxx"` is a placeholder for fields that could be added. I'm going to open up an issue for each field that I'd like to see
- `"yyy": "yyy"` is a placeholder for more general fields. 
- Indentation does not matter. Could be a 1-liner for quicker downloads.

## Describe alternatives you've considered
I'm open for suggestions.

**Comment by nileplumb** [comment]
So long as very simple to use scripts/apps (eg multiple languages PHP/python/batch/executable etc to support multiple OS and icon manager ability) to generate the file is distributed I'll gladly have a 1 index solution.

I don't fancy manually creating this ever :p

**Comment by ccev** [comment]
Of course this will mostly be automated! Just trying to get the format together.

**Comment by jepke** [comment]
It will need to be fully automated. We can't ask icon creators to go and manually change stuff.

**Comment by ccev** [comment]
By `mostly` I mean a singular suggested field could not be automated: The iconset name. Everything else will be.

**Comment by jepke** [comment]
Icon name in the index is overhead. It will need to be translated for 50% of the projects how will you handle that. Bots and tools most likely do nothing with a name field. Frontend maps will most likely use identifiers in their native language that tell what sort of icons the user can set.

**Comment by versx** [comment]
> Icon name in the index is overhead. It will need to be translated for 50% of the projects how will you handle that. Bots and tools most likely do nothing with a name field. Frontend maps will most likely use identifiers in their native language that tell what sort of icons the user can set.

I 💯 agree with fully automated. One thing I could see would be allowing simple arguments (or a config I guess) for the iconset name and I guess if Malte wanted to go so far as adding author and other not-necessary properties. Although it's definitely not a requirement since the iconset name is likely pre-set in the config of whatever tool is using it. (I do at least, pretty sure pmsf _might_ but not sure)

Maybe we make it an optional field to read if set?

**Comment by ccev** [comment]
Please discuss names in #13. The script could read the name from the index.json and always re-use that. The goal of my index.json suggestions is not to put more load on icon creators, but rather to make it easier for tool devs to work with uicons 🙂

**Comment by jepke** [comment]
Icon creators should only have to spend 99.99% on icons 0.01% should be a click and run script to generate the json. Ideal script imo would be bash or a powershell script both natively run on Linux and windows. This will allow the icon creator to generate the json without the need to install anything like python node etc etc.

Keep it flat, keep it simple, the more complex this gets, the more likely it gets that icons are going to be hard-coded again and projects just going to skip on fallback.
